FROM ubuntu:17.10
LABEL maintainer="Benny Li <dev@benny-li.de>"

# Ensure the container is up-to-date
RUN apt-get update && apt-get upgrade --yes

# Install lynx browser
RUN apt-get install --yes lynx-cur
